<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="generator" content="litedown 0.7.1">
<title>Error signalling: balancing messages and backtraces</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@xiee/utils@1.14.14/css/default.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@xiee/utils@1.14.14/css/article.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@xiee/utils@1.14.14/css/copy-button.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@xiee/utils@1.14.14/css/heading-anchor.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@xiee/utils@1.14.14/css/pages.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@xiee/utils@1.14.14/css/site.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@xiee/utils@1.14.14/css/prism-xcode.min.css">
<script src="https://cdn.jsdelivr.net/npm/@xiee/utils@1.14.14/js/sidenotes.min.js" defer></script>
<script src="https://cdn.jsdelivr.net/npm/@xiee/utils@1.14.14/js/appendix.min.js" defer></script>
<script src="https://cdn.jsdelivr.net/npm/@xiee/utils@1.14.14/js/toc-highlight.min.js" defer></script>
<script src="https://cdn.jsdelivr.net/npm/@xiee/utils@1.14.14/js/copy-button.min.js" defer></script>
<script src="https://cdn.jsdelivr.net/npm/@xiee/utils@1.14.14/js/heading-anchor.min.js" defer></script>
<script src="https://cdn.jsdelivr.net/npm/@xiee/utils@1.14.14/js/pages.min.js" defer></script>
<script src="https://cdn.jsdelivr.net/npm/@xiee/utils@1.14.14/js/external-link.min.js" defer></script>
<script src="https://cdn.jsdelivr.net/npm/prismjs@1.29.0/components/prism-core.min.js" defer></script>
<script src="https://cdn.jsdelivr.net/npm/prismjs@1.29.0/plugins/autoloader/prism-autoloader.min.js" defer></script>
</head>
<body>
<nav><p><strong>June Choe’s Micro Blog</strong> <a href="../index.html">Posts</a> <a href="../about.html">About</a></p></nav>
<div class="frontmatter">
<div class="title"><h1>Error signalling: balancing messages and backtraces</h1></div>
<div class="date"><h3>2025-06-19</h3></div>
</div>
<div class="body">
<div id="TOC">
<ul>
<li><a href="#chp:approach-1-bare-bones-abort">Approach 1: Bare-bones <code>abort()</code></a></li>
<li><a href="#chp:approach-2-using-call-caller-env">Approach 2: Using <code>call = caller_env()</code></a></li>
<li><a href="#chp:approach-3-using-call-caller-call">Approach 3: Using <code>call = caller_call()</code></a></li>
<li><a href="#chp:sessioninfo"><code>sessionInfo()</code></a></li>
</ul>
</div>
<!-- pre-hook -->
<p>When your package throws an error from an internal function, you have to balance how much of that context you want to show to the user. This involves balancing the <strong>error message</strong> with the <strong>backtrace</strong>.</p>
<p>The error message should point to the user’s code - the function that causally led to the problem. The backtrace should show the path down to where the error actually occurred, so that debugging can start from the right place.</p>
<p>I’ll show three approaches to handle this balance, using <code>rlang::abort()</code></p>
<pre><code class="language-r">library(rlang)
</code></pre>
<h1 id="chp:approach-1-bare-bones-abort">Approach 1: Bare-bones <code>abort()</code></h1>
<pre><code class="language-r"># Internal
check1 &lt;- function(x) {
  if (!is.character(x)) abort(&quot;x must be character&quot;)
}
# Exported
my_fun1 &lt;- function(x) check1(x)

my_fun1(123) # Error
last_trace()
</code></pre>
<pre class="language-plain" style="font-size:0px">
  <code class="error language-plain" style="font-size:.9rem">&lt;error/rlang_error&gt;
Error in `check1()`:
! x must be character
---
Backtrace:
    ▆
 1. └─global my_fun1(123)
 2.   └─global check1(x)
Run rlang::last_trace(drop = FALSE) to see 1 hidden frame.</code>
</pre>
<p>The error focuses on the internal function <code>check1()</code>. It’s not very actionable for users in the top-level message, but showing it in the backtrace does help identify the internal source of the error.</p>
<h1 id="chp:approach-2-using-call-caller-env">Approach 2: Using <code>call = caller_env()</code></h1>
<pre><code class="language-r"># Internal
check2 &lt;- function(x) {
  if (!is.character(x)) abort(&quot;x must be character&quot;, call = caller_env())
}
# Exported
my_fun2 &lt;- function(x) check2(x)

my_fun2(123) # Error
last_trace()
</code></pre>
<pre class="language-plain" style="font-size:0px">
  <code class="error language-plain" style="font-size:.9rem">&lt;error/rlang_error&gt;
Error in `my_fun2()`:
! x must be character
---
Backtrace:
    ▆
 1. └─global my_fun2(123)
Run rlang::last_trace(drop = FALSE) to see 2 hidden frames.</code>
</pre>
<p>The error message now points to the user-facing function <code>my_fun2()</code>, which is more actionable. However, only showing the backtrace down to <code>my_fun2()</code> obscures the internal function that actually threw the error. This is redundant and adds friction for the user, who now needs to <code>last_trace(drop = FALSE)</code> to see the full path.</p>
<h1 id="chp:approach-3-using-call-caller-call">Approach 3: Using <code>call = caller_call()</code></h1>
<pre><code class="language-r"># Internal
check3 &lt;- function(x) {
  if (!is.character(x)) abort(&quot;x must be character&quot;, call = caller_call())
}
# Exported
my_fun3 &lt;- function(x) check3(x)

my_fun3(123) # Error
last_trace()
</code></pre>
<pre class="language-plain" style="font-size:0px">
  <code class="error language-plain" style="font-size:.9rem">&lt;error/rlang_error&gt;
Error in `my_fun3()`:
! x must be character
---
Backtrace:
    ▆
 1. └─global my_fun3(123)
 2.   └─global check3(x)
Run rlang::last_trace(drop = FALSE) to see 1 hidden frame.</code>
</pre>
<p>IMO this approach gives you the best of both worlds: the error message points to the user-facing function which is immediately useful, while the backtrace shows the full path down to the internal function which helps further contextualize the error.</p>
<p>The error message and backtrace now serve different purposes instead of being redundant - the error message shows what the user did to cause the error (<code>my_fun3()</code>), and the backtrace shows where things actually went wrong internally (<code>check3()</code>).</p>
<hr />
<p>This post was adapted from a Mastodon exchange: <a href="https://fosstodon.org/@yjunechoe/113403050254737010">https://fosstodon.org/@yjunechoe/113403050254737010</a></p>
<!-- post-hook -->
<h1 id="chp:sessioninfo"><code>sessionInfo()</code></h1>
<details>
<summary>Session info</summary>
<pre><code class="language-r">sessionInfo()
</code></pre>
<pre><code>#&gt; R version 4.4.1 (2024-06-14 ucrt)
#&gt; Platform: x86_64-w64-mingw32/x64
#&gt; Running under: Windows 11 x64 (build 26100)
#&gt; 
#&gt; Matrix products: default
#&gt; 
#&gt; 
#&gt; locale:
#&gt; [1] LC_COLLATE=English_United States.utf8 
#&gt; [2] LC_CTYPE=English_United States.utf8   
#&gt; [3] LC_MONETARY=English_United States.utf8
#&gt; [4] LC_NUMERIC=C                          
#&gt; [5] LC_TIME=English_United States.utf8    
#&gt; 
#&gt; time zone: America/New_York
#&gt; tzcode source: internal
#&gt; 
#&gt; attached base packages:
#&gt; [1] stats     graphics  grDevices utils     datasets  methods   base     
#&gt; 
#&gt; other attached packages:
#&gt; [1] htmltools_0.5.8.1 rlang_1.1.4      
#&gt; 
#&gt; loaded via a namespace (and not attached):
#&gt;  [1] compiler_4.4.1         fastmap_1.2.0          litedown_0.7.1        
#&gt;  [4] cli_3.6.3              tools_4.4.1            rstudioapi_0.17.1.9000
#&gt;  [7] codetools_0.2-20       digest_0.6.35          xfun_0.52             
#&gt; [10] commonmark_1.9.5      
</code></pre>
</details>
</div>
<footer><p>© 2025 <a href="https://yjunechoe.github.io/">June Choe</a>.
Site built with <a href="https://github.com/yihui/litedown">litedown</a>.
<img src="https://i.creativecommons.org/l/by/4.0/80x15.png" alt="CC BY" /> <a href="http://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>.</p></footer>
</body>
</html>
